### PR TITLE
Update weapons.db

### PR DESCRIPTION
**Pull request by elfonochasis**
1 needed before dice type. Example d8 -> 1d8

imagen

### CODE REVIEW

**Comment by Futil** [comment]
Thanks for bringing this up! I actually purposefully left out the '1' from the compendium weapons to better match how the cards look in the game. It should still roll the same as 1d6, or 1d8.

Here's a pic of one of the actual game cards as an example.
image

**Comment by elfonochasis** [comment]
It's give me error without '1'.. I had to clone compendium and modify each weapon because i cant make attack roll from sheet

**Comment by Futil** [comment]
Interesting. I'll look into it, thanks for bringing this up

**Comment by Futil** [comment]
Out of curiosity, if you try '/r d6' in the chat, does it provide the same error?

**Comment by Futil** [comment]
I've found the source of the error, this seems to be a bug with the most recent release of Foundry. They've released a hotfix, but as far as I can tell it's not part of the official build yet.

You can find out more on how to fix it here: https://discord.com/channels/170995199584108546/784244473261588480/784490927212855317

In the meantime I am temporarily merging your changes until Foundry fixes this error. Thanks for bringing this to my attention.

**Pull request merged**
